### ISSUE TITLE
FEATURE: Put this plugin on the main page

### ISSUE THREAD

**Issue by lumbar527** [OcelotWalrus/Cromha-Expansion-plugin#111]
**Describe the solution you'd like**
I think it would be cool if this plugin was displayed on the main plugin page (https://endless-sky.github.io/plugins.html). It would likely increase the help received on this project and would also just let more people experience it.

**Required effort**
The main limitation I see it copyright. You would have to go through all the images, stating what is yours and what is derived from other's work. If you want to do this, I can help with making a list of everything.

**Comment by OcelotWalrus** [comment]
Good idea. I will take care of credits and everything don't worry. I'll let you know when it will be finished.

**Comment by lumbar527** [comment]
Thanks!

**Comment by OcelotWalrus** [comment]
Do you think this is good?
https://github.com/OcelotWalrus/Cromha-Expansion-plugin/blob/main/CREDITS.md

**Comment by OcelotWalrus** [comment]
The manifest file:
```
name: Cromha Expansion Plugin
authors: @OcelotWalrus/Cromha, @Lumbar527
homepage: https://github.com/OcelotWalrus/Cromha-Expansion-plugin
license: GPL-3.0-or-later
version: v0.0.1
shortDescription: Galaxy expansion plugin with various original stuff.
description: Adds a new civilization to the Korath Space (now named the 'Empire Space'): The Cromha Empire. Also known as 'The Empire', it is a government that dirige a huge part of the north of the Milky Way. It also a very high advanced government, that has kind of remixed outfits and ships from other vanilla governments. They are human but don't directly have contact with human Merchants, they have contact with the Syndicate, the Republic but they don't allow them to enter their territory. Know more about the plugin in the wiki! (or test the game yourself)
url: https://github.com/OcelotWalrus/Cromha-Expansion-plugin/releases/download/v0.0.1-hotfix/Cromha-Expansion-plugin.zip
iconUrl: https://github.com/OcelotWalrus/Cromha-Expansion-plugin/blob/v0.0.1-hotfix/icon.png?raw=true
autoupdate:
  type: tag
  updateUrl: https://github.com/OcelotWalrus/Cromha-Expansion-plugin
  url: https://github.com/OcelotWalrus/Cromha-Expansion-plugin/releases/download/$version-hotfix/Cromha-Expansion-plugin.zip
```
  iconUrl: https://github.com/OcelotWalrus/Cromha-Expansion-plugin/blob/$version-hotfix/icon.png?raw=true
